In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import time

In [2]:
# DESTINATIONS HOME PAGE
url = 'https://fathomaway.com/destinations/'
res = requests.get(url)
soup = BeautifulSoup(res.content, 'lxml')

In [3]:
headers = soup.find_all(attrs={'class':'accordion__title'})

[continent.text for continent in headers]

['North America',
 'Europe',
 'Central America',
 'Caribbean',
 'South America',
 'Middle East',
 'Africa',
 'Asia',
 'Oceania',
 'Antarctica',
 'Outer Space']

In [4]:
countries = soup.find_all(attrs={'class': 'destinations__country'})

[country.text.strip() for country in countries][:10] # first ten

['Canada',
 'United States',
 'Austria',
 'Belgium',
 'Bosnia and Herzegovina',
 'Croatia',
 'Czech Republic',
 'Denmark',
 'England',
 'Estonia']

In [5]:
soup.find_all(attrs={'class': 'destinations__city'})[:5] # first 5

[<a class="destinations__city" href="/north-america/canada/british-columbia/vancouver/">
                         Vancouver
                       </a>,
 <a class="destinations__city" href="/north-america/canada/ontario/toronto/">
                         Toronto
                       </a>,
 <a class="destinations__city" href="/north-america/canada/quebec/montreal/">
                         Montreal
                       </a>,
 <span class="destinations__city">Québec City</span>,
 <a class="destinations__city" href="/north-america/united-states/arizona/scottsdale/">
                         Scottsdale
                       </a>]

In [6]:
# DESTINATIONS LINK TO COUNTRY
url2 = 'https://fathomaway.com/europe/germany/'
res2 = requests.get(url2)
soup2 = BeautifulSoup(res2.content, 'lxml')

In [7]:
soup2.find_all('h6', attrs={'class': "content__title"})

[<h6 class="content__title">Beer, Wine, and Fast Cars Top the Agenda in Stuttgart</h6>,
 <h6 class="content__title">Berlin</h6>,
 <h6 class="content__title">Swissôtel Is the Place to Stay in Dresden, AKA Florence on the Elbe</h6>,
 <h6 class="content__title">Counting the Ways to Love Dresden, from 1 Monkey to 4,909 Diamonds</h6>,
 <h6 class="content__title">Meet Movie Maestro Marko Roth</h6>,
 <h6 class="content__title">Leipzig Is a Second City with First-Rate German Charm</h6>,
 <h6 class="content__title">A Drinking Tour of the Sparkling Rhine</h6>,
 <h6 class="content__title">US Family Seeks Germany Ancestors. No Language Skills Necessary.</h6>]

In [8]:
soup2.find_all('a', attrs={'class': "content__url"})[0]

<a class="content__url" href="/travel-guide-stuttgart-germany/">
<img alt="Canstatter Volkfest Beer Festival in Stuttgart, Germany." class="content__image img-fluid" src="https://s3.amazonaws.com/fathom_media/photos/Canstatter-Volkfest-beer-festival-carnival-rides.jpg.900x600_q85_crop.jpg"/>
</a>

In [9]:
# PARSE CONTENT OF BLOG POST
url3 = 'https://fathomaway.com/wine-tour-frankfurt-germany/'
res3 = requests.get(url3)
soup3 = BeautifulSoup(res3.content, 'lxml')

paragraphs = soup3.find_all(attrs={'class': 'article-detail__main'})

[paragraph.text.replace('\n', '') for paragraph in paragraphs]

['Last time we spoke to Kristin, she was chasing the grape vines in Croatia. She\'s still discovering sparkling apple cider in Germany. FRANKFURT – Mother Nature is feeling generous. After days of chilly, cloudy weather, the early May sun lights up the verdant German landscape. Apple blossoms — white, light pink, fuchsia — form a blushing canopy against the nearly cloudless sky. "In our language of fruit flowers, the intensity of flowers is only like this every three to five years," says apfelwein producer Andreas Schneider. "In this moment, nature gives me the future."I\'m in Germany visiting Obsthof am Steinberg, the only family-run fruit farm in Frankfurt, to sample the region\'s famous golden beverage. Sparkling cider (apfelwein) has a long history, dating back to the 1st century AD when it was enjoyed by the ancient Greeks and Romans. It didn\'t gain popularity in Hessen, a state situated in west-central Germany that encompasses Frankfurt, until the 16th century when cold winters damaged grape vineyards in the area and winemakers were forced to find alternatives. Apple trees flourished in cold winters, so growers abandoned their vineyards for apple orchards and started producing a tart cider with a lower alcohol content — around five to seven percent. Apple wine is known to strengthen the immune system, promote mental vitality, and help prevent heart and cardiovascular diseases. It is traditionally served in a bembel, a light gray and blue earthenware pitcher.Sparkling apple wine and a traditional bembel.Schneider pours me a glass from his charming bembel, which reads "Obsthof am Steinberg" in blue, hand-painted letters. He oversees the orchard that his parents planted, which celebrated its 50th anniversary last year. "I grew up on this farm," Schneider says. "This was my playground as a child. I climbed trees; I cut them. Every job on this farm I learned." Early on, Schneider knew apple farming was his calling: He left high school to do an apprenticeship as a fruit farmer for three years in nearby Kriftel.For the past twenty years, Schneider Obsthof am Steinberg has farmed organically using a clever ampoule system: Each small vessel contains the sexual pheromone of female pests, which confuses the males so they don\'t procreate, resulting in fewer pests to harm the crops. The property has 250 varieties of fruit, including cherries, pears, and strawberries. Twenty-five workers harvest the fruits by hand, including 120 apple varieties, with more heirloom varieties added to the orchard each year. Companies like Jumeirah Frankfurt (my hotel for the trip) can sponsor apple trees, thereby safeguarding heirloom varieties for the future. Schneider plants both modern orchards, which take ten years to mature, and traditional orchards with high stem trees, which take twenty to twenty-five years to mature. "High stem trees are like typewriters — many people don\'t grow them anymore, but they produce unique copy," Schneider says.Apple blossoms in bloom.Uwe\'s son, Simon, explains the riddling process and shows sediment at the bottom of the bottles.In another area of Hessen called Hochheim am Main, near the confluence of the Main and Rhine rivers, Weingut Schreiber produces sparkling wine using the riddling board method. Madame Clicquot (of Veuve Clicquot fame) developed riddling in France\'s Champagne region in 1816. The labor-intensive method paved the way for clear wine; it had theretofore been cloudy due to yeast and sediments. The riddling process collects yeast and sediment in the bottle and concentrates it near the mouth. After initial fermentation, bottles are stored neck-down at a 45-degree angle on a riddling rack made from two rectangular boards hinged at the top; each side has holes that hold the necks of the bottles. Over the next few weeks, the winemaker rotates every bottle a few degrees each day. After riddling is complete, the bottles are disgorged. Crown caps are removed, and the pressure within the bottles shoots out the sediment. Once the sediment is expelled, the bottle is quickly corked.The modern way freezes the neck of the bottle, resulting in the frozen sediment popping out in an icy chunk. Winemaker Uwe Schreiber still rotates bottles by hand and sometimes employs the old disgorging method he learned in Champagne 30 years ago: a very fast tilt of the bottle that requires timing, practice, and skill. The sediment spurts out, and he contains the remainder of the clear sparkling wine in the bottle with his thumb. "After a half million bottles, I think I have finally mastered it," he laughs.Weingut Schreiber produces 60,000 bottles annually, half of which are sparkling wine, in addition to delicious German Rieslings and other varietals. The family has a storied legacy in Hochheim: The first Schreiber produced wine in 1752. Now they use organic farming techniques due in part to the influence of Uwe\'s son, Simon, who studied winemaking and spent a year learning techniques in New Zealand. "All the young winegrowers want to protect nature," Simon says. A return to traditional organic methods is good for the environment and for the future of winemaking, producing a taste as individual as a human fingerprint.PLAN YOUR TRIPThe wineries are about a little more than a half hour from Frankfurt and make for easy day trips. Frankfurt International Airport (FRA) is only 12 km from the center of town and is a central European hub. (Lufthansa has 22 nonstop flights from North American gateways.) You can rent a car at the airport or arrange transportation from town.Visiting Obsthof am SteinbergVisits: The orchard organizes regular public events (€17-20 per person) as well as private tastings and tours (minimum ten people, approximately €30 per person). Email info@obsthof-am-steinberg.de or call +49-6101-41522 to make a reservation.Train: The journey by train to Nieder-Erlenbach takes about 45 minutes, including a short walk from the station. Click here for schedules.Taxi: A one-way taxi to Schneider Obsthof am Steinberg from Frankfurt Main train station costs approximately €40.Weingut SchreiberVisits: The winery has an open door policy: People can stop by and sample wines they would like to purchase free of charge. Individual and group tours and tastings are customized depending on wines and food. A one-hour tractor-and-trailer vineyard tour plus tasting of five Schreiber wines costs €20 per person.Train:\xa0Take the nonstop S1 train from Frankfurt Main station to Hochheim (Main) Bahnhof, a 35-minute journey. From the train station, guests can call a taxi (+49-6146-4343) for the remaining 5 km ride to the winery, which should cost around €15.Taxi:\xa0Expect to pay around €55 per way from central Frankfurt.BUT WAIT, THERE\'S MOREOff The Press: A Cider Scene Brews in New YorkChasing the Vines Through DalmatiaA South American Wine Worth the Plane Ticket']

In [58]:
text = text.join([paragraph.text.replace('\n', '') for paragraph in paragraphs])
text

'Last time we spoke to Kristin, she was chasing the grape vines in Croatia. She\'s still discovering sparkling apple cider in Germany. FRANKFURT – Mother Nature is feeling generous. After days of chilly, cloudy weather, the early May sun lights up the verdant German landscape. Apple blossoms — white, light pink, fuchsia — form a blushing canopy against the nearly cloudless sky. "In our language of fruit flowers, the intensity of flowers is only like this every three to five years," says apfelwein producer Andreas Schneider. "In this moment, nature gives me the future."I\'m in Germany visiting Obsthof am Steinberg, the only family-run fruit farm in Frankfurt, to sample the region\'s famous golden beverage. Sparkling cider (apfelwein) has a long history, dating back to the 1st century AD when it was enjoyed by the ancient Greeks and Romans. It didn\'t gain popularity in Hessen, a state situated in west-central Germany that encompasses Frankfurt, until the 16th century when cold winters damaged grape vineyards in the area and winemakers were forced to find alternatives. Apple trees flourished in cold winters, so growers abandoned their vineyards for apple orchards and started producing a tart cider with a lower alcohol content — around five to seven percent. Apple wine is known to strengthen the immune system, promote mental vitality, and help prevent heart and cardiovascular diseases. It is traditionally served in a bembel, a light gray and blue earthenware pitcher.Sparkling apple wine and a traditional bembel.Schneider pours me a glass from his charming bembel, which reads "Obsthof am Steinberg" in blue, hand-painted letters. He oversees the orchard that his parents planted, which celebrated its 50th anniversary last year. "I grew up on this farm," Schneider says. "This was my playground as a child. I climbed trees; I cut them. Every job on this farm I learned." Early on, Schneider knew apple farming was his calling: He left high school to do an apprenticeship as a fruit farmer for three years in nearby Kriftel.For the past twenty years, Schneider Obsthof am Steinberg has farmed organically using a clever ampoule system: Each small vessel contains the sexual pheromone of female pests, which confuses the males so they don\'t procreate, resulting in fewer pests to harm the crops. The property has 250 varieties of fruit, including cherries, pears, and strawberries. Twenty-five workers harvest the fruits by hand, including 120 apple varieties, with more heirloom varieties added to the orchard each year. Companies like Jumeirah Frankfurt (my hotel for the trip) can sponsor apple trees, thereby safeguarding heirloom varieties for the future. Schneider plants both modern orchards, which take ten years to mature, and traditional orchards with high stem trees, which take twenty to twenty-five years to mature. "High stem trees are like typewriters — many people don\'t grow them anymore, but they produce unique copy," Schneider says.Apple blossoms in bloom.Uwe\'s son, Simon, explains the riddling process and shows sediment at the bottom of the bottles.In another area of Hessen called Hochheim am Main, near the confluence of the Main and Rhine rivers, Weingut Schreiber produces sparkling wine using the riddling board method. Madame Clicquot (of Veuve Clicquot fame) developed riddling in France\'s Champagne region in 1816. The labor-intensive method paved the way for clear wine; it had theretofore been cloudy due to yeast and sediments. The riddling process collects yeast and sediment in the bottle and concentrates it near the mouth. After initial fermentation, bottles are stored neck-down at a 45-degree angle on a riddling rack made from two rectangular boards hinged at the top; each side has holes that hold the necks of the bottles. Over the next few weeks, the winemaker rotates every bottle a few degrees each day. After riddling is complete, the bottles are disgorged. Crown caps are removed, and the pressure within the bottles shoots out the sediment. Once the sediment is expelled, the bottle is quickly corked.The modern way freezes the neck of the bottle, resulting in the frozen sediment popping out in an icy chunk. Winemaker Uwe Schreiber still rotates bottles by hand and sometimes employs the old disgorging method he learned in Champagne 30 years ago: a very fast tilt of the bottle that requires timing, practice, and skill. The sediment spurts out, and he contains the remainder of the clear sparkling wine in the bottle with his thumb. "After a half million bottles, I think I have finally mastered it," he laughs.Weingut Schreiber produces 60,000 bottles annually, half of which are sparkling wine, in addition to delicious German Rieslings and other varietals. The family has a storied legacy in Hochheim: The first Schreiber produced wine in 1752. Now they use organic farming techniques due in part to the influence of Uwe\'s son, Simon, who studied winemaking and spent a year learning techniques in New Zealand. "All the young winegrowers want to protect nature," Simon says. A return to traditional organic methods is good for the environment and for the future of winemaking, producing a taste as individual as a human fingerprint.PLAN YOUR TRIPThe wineries are about a little more than a half hour from Frankfurt and make for easy day trips. Frankfurt International Airport (FRA) is only 12 km from the center of town and is a central European hub. (Lufthansa has 22 nonstop flights from North American gateways.) You can rent a car at the airport or arrange transportation from town.Visiting Obsthof am SteinbergVisits: The orchard organizes regular public events (€17-20 per person) as well as private tastings and tours (minimum ten people, approximately €30 per person). Email info@obsthof-am-steinberg.de or call +49-6101-41522 to make a reservation.Train: The journey by train to Nieder-Erlenbach takes about 45 minutes, including a short walk from the station. Click here for schedules.Taxi: A one-way taxi to Schneider Obsthof am Steinberg from Frankfurt Main train station costs approximately €40.Weingut SchreiberVisits: The winery has an open door policy: People can stop by and sample wines they would like to purchase free of charge. Individual and group tours and tastings are customized depending on wines and food. A one-hour tractor-and-trailer vineyard tour plus tasting of five Schreiber wines costs €20 per person.Train:\xa0Take the nonstop S1 train from Frankfurt Main station to Hochheim (Main) Bahnhof, a 35-minute journey. From the train station, guests can call a taxi (+49-6146-4343) for the remaining 5 km ride to the winery, which should cost around €15.Taxi:\xa0Expect to pay around €55 per way from central Frankfurt.BUT WAIT, THERE\'S MOREOff The Press: A Cider Scene Brews in New YorkChasing the Vines Through DalmatiaA South American Wine Worth the Plane Ticket'

In [10]:
soup3.find(attrs={'class': 'article-detail__header'}).text

'A Drinking Tour of the Sparkling Rhine'

In [11]:
# SEARCH BY COUNTRY PROFILE
url4 = 'https://fathomaway.com/Germany/'
res4 = requests.get(url4)
soup4 = BeautifulSoup(res4.content, 'lxml')

In [12]:
articles = soup4.find_all(attrs={'class': 'content__url'})

In [13]:
[link.attrs['href'] for link in articles]

['/first-impressions-guide-berlin-germany/',
 '/first-impressions-guide-berlin-germany/',
 '/bar-crawl-guide-munich-germany/',
 '/bar-crawl-guide-munich-germany/',
 '/travel-guide-stuttgart-germany/',
 '/travel-guide-stuttgart-germany/',
 '/travel-guide-franconia-germany/',
 '/travel-guide-franconia-germany/',
 '/munich-berlin-photo-tour/',
 '/munich-berlin-photo-tour/',
 '/interview-hutto-project-refugee-camp-berlin/',
 '/interview-hutto-project-refugee-camp-berlin/',
 '/best-of-arts-and-culture/',
 '/best-of-arts-and-culture/',
 '/what-to-do-in-dresden-germany/',
 '/what-to-do-in-dresden-germany/',
 '/best-new-hotel-openings-summer-2017/',
 '/best-new-hotel-openings-summer-2017/',
 '/what-to-do-in-Leipzig/',
 '/what-to-do-in-Leipzig/',
 '/wine-tour-frankfurt-germany/',
 '/wine-tour-frankfurt-germany/',
 '/love-lock-bridges-around-the-world/',
 '/love-lock-bridges-around-the-world/',
 '/schottenfreude-ben-schott/',
 '/schottenfreude-ben-schott/',
 '/looking-for-relatives-ulm-germany/',
 '/looking-for-relatives-ulm-germany/',
 '/round-the-world-trip-photo-story/',
 '/round-the-world-trip-photo-story/',
 '/love-letter-hotel-adlon-berlin/',
 '/love-letter-hotel-adlon-berlin/',
 '/romantic-travel-winter-2016/',
 '/romantic-travel-winter-2016/',
 '/where-to-celebrate-30th-birthday/',
 '/where-to-celebrate-30th-birthday/',
 '/european-beauty-buys/',
 '/european-beauty-buys/',
 '/instatrip-fun-in-northern-europe/',
 '/instatrip-fun-in-northern-europe/']

In [14]:
captions = soup4.find_all('figcaption')#.find_all('href')
# caption.attrs['href']#[0].find_all(attrs={'class': 'content__url'})
[tag.attrs for tag in captions]

[{'class': ['content__figcaption']},
 {'class': ['content__figcaption']},
 {'class': ['content__figcaption']},
 {'class': ['content__figcaption']},
 {'class': ['content__figcaption']},
 {'class': ['content__figcaption']},
 {'class': ['content__figcaption']},
 {'class': ['content__figcaption']},
 {'class': ['content__figcaption']},
 {'class': ['content__figcaption']},
 {'class': ['content__figcaption']},
 {'class': ['content__figcaption']},
 {'class': ['content__figcaption']},
 {'class': ['content__figcaption']},
 {'class': ['content__figcaption']},
 {'class': ['content__figcaption']},
 {'class': ['content__figcaption']},
 {'class': ['content__figcaption']},
 {'class': ['content__figcaption']},
 {'class': ['content__figcaption']}]

In [15]:
article_urls = []
for n in range(len(soup4.find_all('figcaption'))):
    article_urls.append(soup4.find_all('figcaption')[n].find_all(attrs={'class': 'content__url'}))
article_urls

[[<a class="content__url" href="/first-impressions-guide-berlin-germany/">
  <h6 class="content__title">First Impressions of Berlin From a Longtime Fan</h6>
  </a>],
 [<a class="content__url" href="/bar-crawl-guide-munich-germany/">
  <h6 class="content__title">Pröst! A Bar Crawl Through Münich</h6>
  </a>],
 [<a class="content__url" href="/travel-guide-stuttgart-germany/">
  <h6 class="content__title">Beer, Wine, and Fast Cars Top the Agenda in Stuttgart</h6>
  </a>],
 [<a class="content__url" href="/travel-guide-franconia-germany/">
  <h6 class="content__title">Oktoberfest Means Wine in Franconia, the Enchanting German Region You Don't Know Yet</h6>
  </a>],
 [<a class="content__url" href="/munich-berlin-photo-tour/">
  <h6 class="content__title">A Picture-Perfect Tour of Munich and Berlin</h6>
  </a>],
 [<a class="content__url" href="/interview-hutto-project-refugee-camp-berlin/">
  <h6 class="content__title">At This Refugee Camp in Berlin, Relief Hits High and Low Notes</h6>
  </a>],
 [<a class="content__url" href="/best-of-arts-and-culture/">
  <h6 class="content__title">7 Culture Stops to Make Before You Party Like an Idiot in Berlin</h6>
  </a>],
 [<a class="content__url" href="/what-to-do-in-dresden-germany/">
  <h6 class="content__title">Counting the Ways to Love Dresden, from 1 Monkey to 4,909 Diamonds</h6>
  </a>],
 [<a class="content__url" href="/best-new-hotel-openings-summer-2017/">
  <h6 class="content__title">The 16 Hottest Hotel Openings for Summer 2017</h6>
  </a>],
 [<a class="content__url" href="/what-to-do-in-Leipzig/">
  <h6 class="content__title">Leipzig Is a Second City with First-Rate German Charm</h6>
  </a>],
 [<a class="content__url" href="/wine-tour-frankfurt-germany/">
  <h6 class="content__title">A Drinking Tour of the Sparkling Rhine</h6>
  </a>],
 [<a class="content__url" href="/love-lock-bridges-around-the-world/">
  <h6 class="content__title">Romance on the Road: 10 Unexpected Places to Leave a Love Lock</h6>
  </a>],
 [<a class="content__url" href="/schottenfreude-ben-schott/">
  <h6 class="content__title">Germans Will Be Germans. In Any Language.</h6>
  </a>],
 [<a class="content__url" href="/looking-for-relatives-ulm-germany/">
  <h6 class="content__title">US Family Seeks Germany Ancestors. No Language Skills Necessary.</h6>
  </a>],
 [<a class="content__url" href="/round-the-world-trip-photo-story/">
  <h6 class="content__title">Around the World in 547 Days</h6>
  </a>],
 [<a class="content__url" href="/love-letter-hotel-adlon-berlin/">
  <h6 class="content__title">Berlin's Hotel Adlon</h6>
  </a>],
 [<a class="content__url" href="/romantic-travel-winter-2016/">
  <h6 class="content__title">Holiday 2016: Travel With Lovers</h6>
  </a>],
 [<a class="content__url" href="/where-to-celebrate-30th-birthday/">
  <h6 class="content__title">Where to Go for a Thrilling 30th Birthday Party</h6>
  </a>],
 [<a class="content__url" href="/european-beauty-buys/">
  <h6 class="content__title">8 European Beauty Buys You’ll Never Throw Out</h6>
  </a>],
 [<a class="content__url" href="/instatrip-fun-in-northern-europe/">
  <h6 class="content__title">The Sleepless North</h6>
  </a>]]

In [16]:
#SEARCH COUNTRY
url5 = 'https://fathomaway.com/search/?q=france' #&page=2'
res5 = requests.get(url5)
soup5 = BeautifulSoup(res5.content, 'lxml')

In [17]:
soup5.find_all(attrs={'class': 'content__url'})[0]

<a class="content__url" href="/travel-guide-languedoc-roussillon-france/">
<img alt="Chateau L'Hospitalet in Narbonne, Languedoc-Roussillon, France." class="content__image img-fluid" src="https://s3.amazonaws.com/fathom_media/photos/France-Narbonne-Chateau-LHospitalet-main.jpg.270x180_q85_crop.jpg"/>
</a>

In [18]:
soup5.find_all(attrs={'class': 'content__title'})

[<h6 class="content__title">Sips, Salts, and Soirées: Exploring the Untapped Regions of France’s Languedoc-Roussillon</h6>,
 <h6 class="content__title">Handmade France: An Artisan Road Trip</h6>,
 <h6 class="content__title">The Côte d'Azur Is My Perfect Escape</h6>,
 <h6 class="content__title">Laid Back in Brittany</h6>,
 <h6 class="content__title">Weekend Drive from Monaco: Zip Around Nice &amp; Cote d'Azur</h6>,
 <h6 class="content__title">Carb-Free and Booze-less in Bordeaux: Why I Won't Let My Diet Restrict My Travels</h6>,
 <h6 class="content__title">Explore — and Drink! — Champagne Like an Winemaker</h6>,
 <h6 class="content__title">An Elegant, Fashionable, Architecturally Notable Holiday Resort? Of Course It’s French</h6>,
 <h6 class="content__title">What's in a Word: Curious Expressions From Around the World</h6>,
 <h6 class="content__title">Village Hopping from Nice to Monaco</h6>,
 <h6 class="content__title">In Normandy, It’s a Family Affair for This Parisian Designer</h6>,
 <h6 class="content__title">In Praise of Pastis: An Ode to the Evening Aperitif</h6>]

In [19]:
# MAX PAGE NUMBER
soup5.find_all(attrs={'class': 'pagination__link'})[-2].text

'29'

In [20]:
#SEARCH COUNTRY  BY MAX PAGE NUMBER
url6 = 'https://fathomaway.com/search/?q=france&page=29'
res6 = requests.get(url6)
soup6 = BeautifulSoup(res6.content, 'lxml')

In [21]:
articles2 = soup6.find_all(attrs={'class': 'content__url'})
[link.attrs['href'] for link in articles2]

['/literary-tour-of-paris/',
 '/literary-tour-of-paris/',
 '/contemporary-bars-restaurants-museums-rome/',
 '/contemporary-bars-restaurants-museums-rome/',
 '/where-to-drink-cider-new-york/',
 '/where-to-drink-cider-new-york/',
 '/most-romantic-hotels-2019/',
 '/most-romantic-hotels-2019/',
 '/what-to-do-in-anguilla/',
 '/what-to-do-in-anguilla/',
 '/24-best-hotel-openings-2017/',
 '/24-best-hotel-openings-2017/',
 '/itinerary-istria-croatia/',
 '/itinerary-istria-croatia/',
 '/timely-travel-deals-news-2018/',
 '/timely-travel-deals-news-2018/']

In [22]:
# soup6.find().find_all(attrs={'class': 'content__url'})

In [23]:
articles = []
for link in soup6.find_all(attrs={'class': 'content__url'}):
    article = {}
    article['href'] = link.attrs['href']
    article['title'] = link.text.strip()
    articles.append(article)

pd.DataFrame(articles)

,href,title
0,/literary-tour-of-paris/,
1,/literary-tour-of-paris/,Hemingway Slept Here: A Literary Tour of Paris
2,/contemporary-bars-restaurants-museums-rome/,
3,/contemporary-bars-restaurants-museums-rome/,Where Young Creatives Hang in Rome
4,/where-to-drink-cider-new-york/,
5,/where-to-drink-cider-new-york/,Off The Press: A Cider Scene Brews in New York
6,/most-romantic-hotels-2019/,
7,/most-romantic-hotels-2019/,The World's Most Romantic Hotels 2019: You Lov...
8,/what-to-do-in-anguilla/,
9,/what-to-do-in-anguilla/,"You May Not Know It Yet, But You Belong in Ang..."
10,/24-best-hotel-openings-2017/,
11,/24-best-hotel-openings-2017/,Coming Soon: The 24 Best Hotel Openings of 2017
12,/itinerary-istria-croatia/,
13,/itinerary-istria-croatia/,"Don't Tell Italy, But We Might Like Istria Better"
14,/timely-travel-deals-news-2018/,
15,/timely-travel-deals-news-2018/,Timely Travel Deals & News from 2018

## Recommendations with J
- pick 30 or so countries to model with
- predict country from blog = meh.
- estimate & compare relationship (or frequency) of certain words among various countries
- feed blog post into model to output list of related countries
- predict country to visit from fb posts of a user
- use TFIDF for word count comparison
- use Word2Vec to establish relationship among words from bloggers to country (need same number of blog posts per country)

In [152]:
advisory = pd.Series(pd.read_json('https://www.travel-advisory.info/api')['data'])
df_advisory = pd.DataFrame([item for item in advisory[2:]])

df_advisory_return = pd.DataFrame([item for item in df_advisory['advisory']])

for col in df_advisory_return.columns:
    df_advisory[col] = df_advisory_return[col]
df_advisory.drop(columns='advisory', inplace=True)

In [159]:
df_advisory

,iso_alpha2,name,continent,score,sources_active,message,updated,source
0,AD,Andorra,EU,1.3,3,,2020-03-05 07:19:48,https://www.travel-advisory.info/andorra
1,AE,United Arab Emirates,AS,2.3,6,,2020-03-05 07:19:48,https://www.travel-advisory.info/united-arab-e...
2,AF,Afghanistan,AS,5.0,10,,2020-03-05 07:19:48,https://www.travel-advisory.info/afghanistan
3,AG,Antigua and Barbuda,NA,1.0,2,,2020-03-05 07:19:48,https://www.travel-advisory.info/antigua-and-b...
4,AI,Anguilla,NA,1.0,2,,2020-03-05 07:19:48,https://www.travel-advisory.info/anguilla
...,...,...,...,...,...,...,...,...
233,YE,Yemen,AS,5.0,9,,2020-03-05 07:19:48,https://www.travel-advisory.info/yemen
234,YT,Mayotte,AF,3.0,1,,2020-03-05 07:19:48,https://www.travel-advisory.info/mayotte
235,ZA,South Africa,AF,2.7,6,,2020-03-05 07:19:48,https://www.travel-advisory.info/south-africa
236,ZM,Zambia,AF,2.0,3,,2020-03-05 07:19:48,https://www.travel-advisory.info/zambia
237,ZW,Zimbabwe,AF,2.6,5,,2020-03-05 07:19:48,https://www.travel-advisory.info/zimbabwe

## TOP 20 COUNTRIES

In [24]:
# GET TOP TOURISM COUNTRIES
df_tourism = pd.read_csv('./data/most_traveled_countries.csv')
# SOURCE: http://worldpopulationreview.com/countries/most-visited-countries/
df_tourism

                  name  touristArrivals  tourismReceipts      pop2019
0               France         82700000      54531000000    65129.728
1        United States         76407000     206902000000   329064.917
2                Spain         75315000      60503000000    46736.776
3                China         59270000      44432000000  1433783.686
4                Italy         52372000      40246000000    60550.075
..                 ...              ...              ...          ...
176      Guinea-Bissau            22000       1319000000     1920.922
177       Turkmenistan                0                0     5942.089
178              Libya                0         60000000     6777.452
179              Gabon                0                0     2172.579
180  Equatorial Guinea                0                0     1355.986

[181 rows x 4 columns]

In [160]:
df_countries = pd.merge(df_advisory, df_tourism, on='name')
df_countries

,iso_alpha2,name,continent,score,sources_active,message,updated,source,touristArrivals,tourismReceipts,pop2019
0,AD,Andorra,EU,1.3,3,,2020-03-05 07:19:48,https://www.travel-advisory.info/andorra,2831000,0,77.142
1,AE,United Arab Emirates,AS,2.3,6,,2020-03-05 07:19:48,https://www.travel-advisory.info/united-arab-e...,14870000,19496000000,9770.529
2,AL,Albania,EU,1.5,4,,2020-03-05 07:19:48,https://www.travel-advisory.info/albania,4070000,1691000000,2880.917
3,AM,Armenia,AS,1.5,4,,2020-03-05 07:19:48,https://www.travel-advisory.info/armenia,1260000,968000000,2957.731
4,AO,Angola,AF,2.0,5,,2020-03-05 07:19:48,https://www.travel-advisory.info/angola,397000,623000000,31825.295
...,...,...,...,...,...,...,...,...,...,...,...
173,VN,Vietnam,AS,1.8,5,,2020-03-05 07:19:48,https://www.travel-advisory.info/vietnam,10013000,8250000000,96462.106
174,YE,Yemen,AS,5.0,9,,2020-03-05 07:19:48,https://www.travel-advisory.info/yemen,1025000,1161000000,29161.922
175,ZA,South Africa,AF,2.7,6,,2020-03-05 07:19:48,https://www.travel-advisory.info/south-africa,10044000,7910000000,58558.270
176,ZM,Zambia,AF,2.0,3,,2020-03-05 07:19:48,https://www.travel-advisory.info/zambia,956000,683000000,17861.030
177,ZW,Zimbabwe,AF,2.6,5,,2020-03-05 07:19:48,https://www.travel-advisory.info/zimbabwe,2168000,890000000,14645.468

In [167]:
for country in df_tourism['name']:
    if country not in list(df_countries['name']):
        print(country)

United States Virgin Islands
Palestine
DR Congo

In [168]:
for country in df_advisory['name']:
    if country not in list(df_countries['name']):
        print(country)

Afghanistan
Antigua and Barbuda
Anguilla
American Samoa
Saint Barthélemy
Belize
Cocos Islands
Democratic Republic of the Congo
Cook Islands
Christmas Island
Western Sahara
Falkland Islands
Micronesia
Faroe Islands
Guernsey
Gibraltar
Greenland
South Georgia and the South Sandwich Islands
Guam
Isle of Man
Jersey
Kiribati
Comoros
Saint Kitts and Nevis
North Korea
Liberia
Saint Martin
Marshall Islands
Macedonia
Macao
Northern Mariana Islands
Mauritania
Montserrat
New Caledonia
Norfolk Island
Niue
Papua New Guinea
Saint Pierre and Miquelon
Pitcairn
Palestinian Territory
Palau
Solomon Islands
Saint Helena
Svalbard and Jan Mayen
Somalia
South Sudan
Sao Tome and Principe
Swaziland
Turks and Caicos Islands
East Timor
Tonga
Tuvalu
Vatican
Saint Vincent and the Grenadines
U.S. Virgin Islands
Vanuatu
Wallis and Futuna
Samoa
Kosovo
Mayotte

In [172]:
df_countries['name'].to_csv('./data/country_names.csv', index=False)

In [177]:
country_names = [c_name for c_name in pd.read_csv('/Users/meggan/dsi-10/portfolio/capstone/data/country_names.csv')['name']]

In [178]:
country_names

['Andorra',
 'United Arab Emirates',
 'Albania',
 'Armenia',
 'Angola',
 'Argentina',
 'Austria',
 'Australia',
 'Aruba',
 'Azerbaijan',
 'Bosnia and Herzegovina',
 'Barbados',
 'Bangladesh',
 'Belgium',
 'Burkina Faso',
 'Bulgaria',
 'Bahrain',
 'Burundi',
 'Benin',
 'Bermuda',
 'Brunei',
 'Bolivia',
 'Brazil',
 'Bahamas',
 'Bhutan',
 'Botswana',
 'Belarus',
 'Canada',
 'Central African Republic',
 'Republic of the Congo',
 'Switzerland',
 'Ivory Coast',
 'Chile',
 'Cameroon',
 'China',
 'Colombia',
 'Costa Rica',
 'Cuba',
 'Cape Verde',
 'Cyprus',
 'Czech Republic',
 'Germany',
 'Djibouti',
 'Denmark',
 'Dominica',
 'Dominican Republic',
 'Algeria',
 'Ecuador',
 'Estonia',
 'Egypt',
 'Eritrea',
 'Spain',
 'Ethiopia',
 'Finland',
 'Fiji',
 'France',
 'Gabon',
 'United Kingdom',
 'Grenada',
 'Georgia',
 'French Guiana',
 'Ghana',
 'Gambia',
 'Guinea',
 'Guadeloupe',
 'Equatorial Guinea',
 'Greece',
 'Guatemala',
 'Guinea-Bissau',
 'Guyana',
 'Hong Kong',
 'Honduras',
 'Croatia',
 'Haiti',
 'Hungary',
 'Indonesia',
 'Ireland',
 'Israel',
 'India',
 'Iraq',
 'Iran',
 'Iceland',
 'Italy',
 'Jamaica',
 'Jordan',
 'Japan',
 'Kenya',
 'Kyrgyzstan',
 'Cambodia',
 'South Korea',
 'Kuwait',
 'Cayman Islands',
 'Kazakhstan',
 'Laos',
 'Lebanon',
 'Saint Lucia',
 'Liechtenstein',
 'Sri Lanka',
 'Lesotho',
 'Lithuania',
 'Luxembourg',
 'Latvia',
 'Libya',
 'Morocco',
 'Monaco',
 'Moldova',
 'Montenegro',
 'Madagascar',
 'Mali',
 'Myanmar',
 'Mongolia',
 'Martinique',
 'Malta',
 'Mauritius',
 'Maldives',
 'Malawi',
 'Mexico',
 'Malaysia',
 'Mozambique',
 'Namibia',
 'Niger',
 'Nigeria',
 'Nicaragua',
 'Netherlands',
 'Norway',
 'Nepal',
 'New Zealand',
 'Oman',
 'Panama',
 'Peru',
 'French Polynesia',
 'Philippines',
 'Pakistan',
 'Poland',
 'Puerto Rico',
 'Portugal',
 'Paraguay',
 'Qatar',
 'Reunion',
 'Romania',
 'Serbia',
 'Russia',
 'Rwanda',
 'Saudi Arabia',
 'Seychelles',
 'Sudan',
 'Sweden',
 'Singapore',
 'Slovenia',
 'Slovakia',
 'Sierra Leone',
 'San Marino',
 'Senegal',
 'Suriname',
 'El Salvador',
 'Syria',
 'Chad',
 'Togo',
 'Thailand',
 'Tajikistan',
 'Turkmenistan',
 'Tunisia',
 'Turkey',
 'Trinidad and Tobago',
 'Taiwan',
 'Tanzania',
 'Ukraine',
 'Uganda',
 'United States',
 'Uruguay',
 'Uzbekistan',
 'Venezuela',
 'British Virgin Islands',
 'Vietnam',
 'Yemen',
 'South Africa',
 'Zambia',
 'Zimbabwe']

In [25]:
top20 = list(df_tourism.sort_values(by='touristArrivals', ascending=False)['name'][:20])
top20

['France',
 'United States',
 'Spain',
 'China',
 'Italy',
 'United Kingdom',
 'Germany',
 'Mexico',
 'Thailand',
 'Turkey',
 'Austria',
 'Malaysia',
 'Hong Kong',
 'Greece',
 'Russia',
 'Japan',
 'Canada',
 'Portugal',
 'Saudi Arabia',
 'Poland']

In [61]:
# FIND THE MAXIMUM PAGES OF BLOG POSTS BY COUNTRY SEARCH
last_pages = {}
for country in top20:
    url_base = f'https://fathomaway.com/search/?q={country}'
    res_ = requests.get(url_base)
    soup_ = BeautifulSoup(res_.content, 'lxml')
    time.sleep(10)
    
    try:
        last_pages[country] =  soup_.find_all(attrs={'class': 'pagination__link'})[-2].text
    except:
        last_pages[country] =  None

last_pages

{'France': '29',
 'United States': '39',
 'Spain': '18',
 'China': '15',
 'Italy': '42',
 'United Kingdom': '4',
 'Germany': '8',
 'Mexico': '30',
 'Thailand': '9',
 'Turkey': '9',
 'Austria': '4',
 'Malaysia': '3',
 'Hong Kong': '10',
 'Greece': '6',
 'Russia': '6',
 'Japan': '23',
 'Canada': '10',
 'Portugal': '8',
 'Saudi Arabia': None,
 'Poland': '3'}

In [69]:
# FIND THE MAXIMUM PAGES OF BLOG POSTS BY COUNTRY FILE
last_pages_ = {}
for country in top20:
    url_base = f'https://fathomaway.com/{country}'
    res_ = requests.get(url_base)
    soup_ = BeautifulSoup(res_.content, 'lxml')
    time.sleep(10)
    
    try:
        last_pages_[country] =  soup_.find_all(attrs={'class': 'pagination__link'})[-2].text
    except:
        last_pages_[country] =  None

last_pages_

{'France': '3',
 'United States': '2',
 'Spain': '3',
 'China': '2',
 'Italy': '6',
 'United Kingdom': None,
 'Germany': None,
 'Mexico': '4',
 'Thailand': '2',
 'Turkey': None,
 'Austria': None,
 'Malaysia': None,
 'Hong Kong': '2',
 'Greece': None,
 'Russia': None,
 'Japan': '3',
 'Canada': '2',
 'Portugal': '2',
 'Saudi Arabia': None,
 'Poland': None}

In [28]:
# foos = []
# for country in ['France']:
#     for num in range(int(last_pages[country])):
#         url_base = f'https://fathomaway.com/search/?q={country}&page={num}'
#         res_ = requests.get(url_base)
#         soup_ = BeautifulSoup(res_.content, 'lxml')
#         time.sleep(10)

#         for link in soup_.find_all(attrs={'class': 'content__url'}):
#             foo = {}
#             foo['href'] = link.attrs['href']
#             foo['title'] = link.text.strip()
#             foo['country'] = country
#             foos.append(foo)

# bar = pd.DataFrame(foos)
# bar.head()

In [64]:
# GET ALL URLS FOR 20 COUNTRIES
articles = []
for country in ['France']: # just France ... vs top20
    print(f'Parsing the {last_pages[country]} pages of articles on {country}.')
    for num in range(int(last_pages[country])):
        url_base = f'https://fathomaway.com/search/?q={country}&page={num}'
        res_ = requests.get(url_base)
        soup_ = BeautifulSoup(res_.content, 'lxml')
        time.sleep(10)

        for link in soup_.find_all(attrs={'class': 'content__url'}):
            article = {}
            article['href'] = link.attrs['href']
            article['title'] = link.text.strip()
            article['country'] = country
            articles.append(article)

df = pd.DataFrame(articles)
# df.to_csv('./data/all_articles.csv')
print(df.shape)
df.head()

Parsing France with 29 pages
(696, 3)

,href,title,country
0,/travel-guide-languedoc-roussillon-france/,,France
1,/travel-guide-languedoc-roussillon-france/,"Sips, Salts, and Soirées: Exploring the Untapp...",France
2,/handmade-france-artisan-road-trip/,,France
3,/handmade-france-artisan-road-trip/,Handmade France: An Artisan Road Trip,France
4,/south-france-cote-dazur-photo-tour/,,France

In [65]:
29*24

696

In [66]:
df = df.sort_values(by='title', ascending=False).drop_duplicates('href').copy()
df.shape

(331, 3)

In [67]:
df.head()

,href,title,country
643,/what-to-do-in-israel/,You Don't Need to Believe in a Higher Power to...,France
505,/will-guidara-favorite-casual-restaurants/,World’s Best Restaurant Winner Will Guidara Pi...,France
205,/little-black-book-wildsams-guide-san-francisco/,Wildsam Field Guide in San Francisco,France
663,/travel-guide-el-salvador/,Why Now Is the Time to Travel to El Salvador,France
679,/top-travel-destinations-2020/,Where to Go in 2020: Our Top 10 Picks,France

In [30]:
df.shape

(470, 3)

In [31]:
df

,href,title,country
0,/travel-guide-languedoc-roussillon-france/,,France
1,/travel-guide-languedoc-roussillon-france/,"Sips, Salts, and Soirées: Exploring the Untapp...",France
2,/handmade-france-artisan-road-trip/,,France
3,/handmade-france-artisan-road-trip/,Handmade France: An Artisan Road Trip,France
4,/south-france-cote-dazur-photo-tour/,,France
...,...,...,...
465,/links-we-love-342017/,Links We Love: 3/4/2017,Poland
466,/what-to-do-warsaw-poland-spotted-by-locals/,,Poland
467,/what-to-do-warsaw-poland-spotted-by-locals/,"Old City, New Format: A Local's Tour of Warsaw...",Poland
468,/best-hotel-openings-spring-summer-2018/,,Poland
469,/best-hotel-openings-spring-summer-2018/,The 17 Hottest Hotel Openings of Spring/Summer...,Poland

In [32]:
df['country'].value_counts()

Malaysia          24
Turkey            24
Canada            24
Mexico            24
Thailand          24
Germany           24
United Kingdom    24
Poland            24
Spain             24
Greece            24
Portugal          24
Russia            24
Italy             24
Japan             24
Austria           24
France            24
China             24
United States     24
Hong Kong         24
Saudi Arabia      14
Name: country, dtype: int64

In [33]:
last_pages = []
for country in top20:
    url_base = f'https://fathomaway.com/search/?q={country}'
    res_ = requests.get(url_base)
    soup_ = BeautifulSoup(res_.content, 'lxml')
    time.sleep(2)
    
    nums = {}
    nums['country'] = country
    try:
        nums['last'] = soup_.find_all(attrs={'class': 'pagination__link'})[-2].text
    except:
        nums['last'] = None
    last_pages.append(nums)

df_last = pd.DataFrame(last_pages)
df_last.head()

         country last
0         France   29
1  United States   39
2          Spain   18
3          China   15
4          Italy   42

In [34]:
df_last

           country  last
0           France    29
1    United States    39
2            Spain    18
3            China    15
4            Italy    42
5   United Kingdom     4
6          Germany     8
7           Mexico    30
8         Thailand     9
9           Turkey     9
10         Austria     4
11        Malaysia     3
12       Hong Kong    10
13          Greece     6
14          Russia     6
15           Japan    23
16          Canada    10
17        Portugal     8
18    Saudi Arabia  None
19          Poland     3

In [51]:
# PARSE CONTENT OF EVERY BLOG POST
content_ls = []
for url in df['href']:
    url_post = f'https://fathomaway.com{url}'
    res_post = requests.get(url_post)
    soup_post = BeautifulSoup(res_post.content, 'lxml')
    
    paragraphs = soup_post.find_all(attrs={'class': 'article-detail__main'})

    text = text.join([paragraph.text.replace('\n', '') for paragraph in paragraphs])
    content_ls.append(text)
    time.sleep(10)

In [63]:
df.to_csv('./data/page_1_articles.csv')

In [ ]:
# UnboundLocalError: local variable 'text' referenced before assignment
# text = '' ???? 
def get_content(df):
    content_ls = []
    for url in df['href']:
        url_post = f'https://fathomaway.com{url}'
        res_post = requests.get(url_post)
        soup_post = BeautifulSoup(res_post.content, 'lxml')

        paragraphs = soup_post.find_all(attrs={'class': 'article-detail__main'})

        text = text.join([paragraph.text.replace('\n', '') for paragraph in paragraphs])
        content_ls.append(text)
        time.sleep(10)
    return content_ls